/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.time.LocalDate;
import java.util.Date;
import static java.util.Date.parse;
import javax.swing.JOptionPane;
import model.DoctorInfo;
import model.EncounterHistory;
import model.PatientInfo;

/**
 *
 * @author kshetrahegde
 */
public class AddPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPatientJPanel
     */
    
    

    EncounterHistory history;

    public AddPatientJPanel(EncounterHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPatName = new javax.swing.JLabel();
        lblPatAge = new javax.swing.JLabel();
        lblPatCity = new javax.swing.JLabel();
        lblPatID = new javax.swing.JLabel();
        lblEncID = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblAssigned = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtPatName = new javax.swing.JTextField();
        txtPatAge = new javax.swing.JTextField();
        txtPatCity = new javax.swing.JTextField();
        txtPatID = new javax.swing.JTextField();
        txtEncID = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        txtPulse = new javax.swing.JTextField();
        txtAssigned = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblReport = new javax.swing.JLabel();
        txtReport = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setText("Add Patient Details");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPatName.setText("Name");

        lblPatAge.setText("Age");

        lblPatCity.setText("City");

        lblPatID.setText("ID");

        lblEncID.setText("Encounter ID");

        lblBP.setText("Heart Rate");

        lblPulse.setText("Pulse");

        lblAssigned.setText("Doc. Assigned");

        lblDate.setText("Date");

        txtPatName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPatNameKeyPressed(evt);
            }
        });

        txtPatAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPatAgeKeyPressed(evt);
            }
        });

        txtPatCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatCityActionPerformed(evt);
            }
        });
        txtPatCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPatCityKeyPressed(evt);
            }
        });

        txtPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatIDActionPerformed(evt);
            }
        });
        txtPatID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPatIDKeyPressed(evt);
            }
        });

        txtEncID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEncIDKeyPressed(evt);
            }
        });

        txtBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPActionPerformed(evt);
            }
        });
        txtBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBPKeyPressed(evt);
            }
        });

        txtPulse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPulseKeyPressed(evt);
            }
        });

        txtAssigned.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAssignedKeyPressed(evt);
            }
        });

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateKeyPressed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 102, 102));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblReport.setText("Report");

        txtReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtReportKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatName)
                            .addComponent(lblPatAge)
                            .addComponent(lblPatCity)
                            .addComponent(lblPatID)
                            .addComponent(lblEncID)
                            .addComponent(lblBP)
                            .addComponent(lblPulse)
                            .addComponent(lblAssigned)
                            .addComponent(lblDate)
                            .addComponent(lblReport))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReport, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBP)
                                .addComponent(txtPatName)
                                .addComponent(txtPatAge)
                                .addComponent(txtPatCity)
                                .addComponent(txtPatID, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEncID, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPulse, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatName)
                    .addComponent(txtPatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatAge)
                    .addComponent(txtPatAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatCity)
                    .addComponent(txtPatCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatID)
                    .addComponent(txtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncID)
                    .addComponent(txtEncID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBP)
                    .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulse)
                    .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssigned)
                    .addComponent(txtAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReport))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatCityActionPerformed

    private void txtPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatIDActionPerformed

    private void txtBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (txtPatName.getText().equals("") || txtPulse.getText().equals("") || txtPatID.getText().equals("") || txtPatCity.getText().equals("") || txtPatAge.getText().equals("") || txtEncID.getText().equals("") ||  txtBP.getText().equals("") || txtAssigned.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all details!");
        } else {

            String patientName = txtPatName.getText();
            int age = Integer.parseInt(txtPatAge.getText());
            String city = txtPatCity.getText();
            int patientId = Integer.parseInt(txtPatID.getText());
            int encounterId = Integer.parseInt(txtEncID.getText());
            int bloodPressure = Integer.parseInt(txtBP.getText());
            int pulse = Integer.parseInt(txtPulse.getText());
            String assignedDoctor = txtAssigned.getText();
            //LocalDate d1 = LocalDate.parse(txtDate.getText());
            
            
            String diagnosis = txtReport.getText();


            
            
            try {
                
                LocalDate d1 = LocalDate.parse(txtDate.getText());
                PatientInfo pi = history.addNewPatient();
                pi.setD1(d1);
                pi.setPatientName(patientName);
                pi.setAge(age);
                pi.setCity(city);
                pi.setPatientId(patientId);
                pi.setEncounterId(encounterId);
                pi.setBloodPressure(bloodPressure);
                pi.setPulse(pulse);
                pi.setAssignedDoctor(assignedDoctor);
                //pi.setD1(d1);
                pi.setDiagnosis(diagnosis);

            JOptionPane.showMessageDialog(this, "Information Added!");

            txtPatName.setText("");
            txtPatAge.setText("");
            txtPatCity.setText("");
            txtPatID.setText("");
            txtEncID.setText("");
            txtBP.setText("");
            txtPulse.setText("");
            txtAssigned.setText("");
            txtDate.setText("");
            txtReport.setText("");
            }
            catch (Exception e) {
                
                JOptionPane.showMessageDialog(this, "Please enter correct date format!");
                
            }

            
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPatNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatNameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter alphabets only!");
            txtPatName.setEditable(false);
        }
        else {
            txtPatName.setEditable(true);
        }
    }//GEN-LAST:event_txtPatNameKeyPressed

    private void txtPatAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatAgeKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter numbers only!");
            txtPatAge.setEditable(false);
        }
        else {
            txtPatAge.setEditable(true);
        }
    }//GEN-LAST:event_txtPatAgeKeyPressed

    private void txtPatCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatCityKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter alphabets only!");
            txtPatCity.setEditable(false);
        }
        else {
            txtPatCity.setEditable(true);
        }
    }//GEN-LAST:event_txtPatCityKeyPressed

    private void txtPatIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatIDKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter numbers only!");
            txtPatID.setEditable(false);
        }
        else {
            txtPatID.setEditable(true);
        }
        
    }//GEN-LAST:event_txtPatIDKeyPressed

    private void txtEncIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEncIDKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter numbers only!");
            txtEncID.setEditable(false);
        }
        else {
            txtEncID.setEditable(true);
        }
    }//GEN-LAST:event_txtEncIDKeyPressed

    private void txtBPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBPKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter numbers only!");
            txtBP.setEditable(false);
        }
        else {
            txtBP.setEditable(true);
        }
    }//GEN-LAST:event_txtBPKeyPressed

    private void txtPulseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPulseKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter numbers only!");
            txtPulse.setEditable(false);
        }
        else {
            txtPulse.setEditable(true);
        }
    }//GEN-LAST:event_txtPulseKeyPressed

    private void txtAssignedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAssignedKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter alphabets only!");
            txtAssigned.setEditable(false);
        }
        else {
            txtAssigned.setEditable(true);
        }
    }//GEN-LAST:event_txtAssignedKeyPressed

    private void txtReportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReportKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)) {
            JOptionPane.showMessageDialog(this, "Please enter alphabets only!");
            txtReport.setEditable(false);
        }
        else {
            txtReport.setEditable(true);
        }
    }//GEN-LAST:event_txtReportKeyPressed

    private void txtDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDateKeyPressed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAssigned;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEncID;
    private javax.swing.JLabel lblPatAge;
    private javax.swing.JLabel lblPatCity;
    private javax.swing.JLabel lblPatID;
    private javax.swing.JLabel lblPatName;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblReport;
    private javax.swing.JTextField txtAssigned;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEncID;
    private javax.swing.JTextField txtPatAge;
    private javax.swing.JTextField txtPatCity;
    private javax.swing.JTextField txtPatID;
    private javax.swing.JTextField txtPatName;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtReport;
    // End of variables declaration//GEN-END:variables
}


