/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.time.LocalDate;
import java.util.Date;
import static java.util.Date.parse;
import javax.swing.JOptionPane;
import model.DoctorInfo;
import model.EncounterHistory;
import model.PatientInfo;

/**
 *
 * @author kshetrahegde
 */
public class AddPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPatientJPanel
     */
    EncounterHistory history;

    public AddPatientJPanel(EncounterHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPatName = new javax.swing.JLabel();
        lblPatAge = new javax.swing.JLabel();
        lblPatCity = new javax.swing.JLabel();
        lblPatID = new javax.swing.JLabel();
        lblEncID = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblAssigned = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtPatName = new javax.swing.JTextField();
        txtPatAge = new javax.swing.JTextField();
        txtPatCity = new javax.swing.JTextField();
        txtPatID = new javax.swing.JTextField();
        txtEncID = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        txtPulse = new javax.swing.JTextField();
        txtAssigned = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("Add Patient Details");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPatName.setText("Name");

        lblPatAge.setText("Age");

        lblPatCity.setText("City");

        lblPatID.setText("ID");

        lblEncID.setText("Encounter ID");

        lblBP.setText("Blood Pressure");

        lblPulse.setText("Pulse");

        lblAssigned.setText("Doc. Assigned");

        lblDate.setText("Date");

        txtPatCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatCityActionPerformed(evt);
            }
        });

        txtPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatIDActionPerformed(evt);
            }
        });

        txtBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatName)
                            .addComponent(lblPatAge)
                            .addComponent(lblPatCity)
                            .addComponent(lblPatID)
                            .addComponent(lblEncID)
                            .addComponent(lblBP)
                            .addComponent(lblPulse)
                            .addComponent(lblAssigned)
                            .addComponent(lblDate))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBP)
                                .addComponent(txtPatName)
                                .addComponent(txtPatAge)
                                .addComponent(txtPatCity)
                                .addComponent(txtPatID, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEncID, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPulse, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatName)
                    .addComponent(txtPatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatAge)
                    .addComponent(txtPatAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatCity)
                    .addComponent(txtPatCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatID)
                    .addComponent(txtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncID)
                    .addComponent(txtEncID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBP)
                    .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulse)
                    .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssigned)
                    .addComponent(txtAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatCityActionPerformed

    private void txtPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatIDActionPerformed

    private void txtBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (txtPatName.getText().equals("") || txtPulse.getText().equals("") || txtPatID.getText().equals("") || txtPatCity.getText().equals("") || txtPatAge.getText().equals("") || txtEncID.getText().equals("") || txtDate.getText().equals("") || txtBP.getText().equals("") || txtAssigned.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all details!");
        } else {

            String patientName = txtPatName.getText();
            int age = Integer.parseInt(txtPatAge.getText());
            String city = txtPatCity.getText();
            int patientId = Integer.parseInt(txtPatID.getText());
            int encounterId = Integer.parseInt(txtEncID.getText());
            int bloodPressure = Integer.parseInt(txtBP.getText());
            int pulse = Integer.parseInt(txtPulse.getText());
            String assignedDoctor = txtAssigned.getText();
            
            //Date d1 = new Date();
            LocalDate d1 = LocalDate.parse(txtDate.getText());
            //java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            //java.time.LocalDate textFieldAsDate = java.time.LocalDate.parse(text, formatter);


            PatientInfo pi = history.addNewPatient();

            pi.setPatientName(patientName);
            pi.setAge(age);
            pi.setCity(city);
            pi.setPatientId(patientId);
            pi.setEncounterId(encounterId);
            pi.setBloodPressure(bloodPressure);
            pi.setPulse(pulse);
            pi.setAssignedDoctor(assignedDoctor);
            pi.setD1(d1);

            JOptionPane.showMessageDialog(this, "Information Added!");

            txtPatName.setText("");
            txtPatAge.setText("");
            txtPatCity.setText("");
            txtPatID.setText("");
            txtEncID.setText("");
            txtBP.setText("");
            txtPulse.setText("");
            txtAssigned.setText("");
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAssigned;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEncID;
    private javax.swing.JLabel lblPatAge;
    private javax.swing.JLabel lblPatCity;
    private javax.swing.JLabel lblPatID;
    private javax.swing.JLabel lblPatName;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JTextField txtAssigned;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEncID;
    private javax.swing.JTextField txtPatAge;
    private javax.swing.JTextField txtPatCity;
    private javax.swing.JTextField txtPatID;
    private javax.swing.JTextField txtPatName;
    private javax.swing.JTextField txtPulse;
    // End of variables declaration//GEN-END:variables
}
