/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.HospitalDirectory;
import model.HospitalHistory;
import javax.swing.JOptionPane;


/**
 *
 * @author kshetrahegde
 */
public class ManageHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospitalJPanel
     */
    HospitalHistory hospitalhistory;
    
    public ManageHospitalJPanel(HospitalHistory hospitalhistory) {
        initComponents();
        
        this.hospitalhistory = hospitalhistory;
        //displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHospital = new javax.swing.JLabel();
        lblHosName = new javax.swing.JLabel();
        lblDocName = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtEmployee = new javax.swing.JTextField();
        txtPopulation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospitalDirectory = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        lblCity = new javax.swing.JLabel();
        txtHospName = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();
        lblEmpl = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lblPopulation = new javax.swing.JLabel();
        txtDocName = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();

        lblHospital.setText("Add Hospital Details");
        lblHospital.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblHosName.setText("Hospital Name");

        lblDocName.setText("Doctor Name");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtPopulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPopulationActionPerformed(evt);
            }
        });

        tblHospitalDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Doctor Name", "City", "Community", "Total Employees", "Population"
            }
        ));
        jScrollPane1.setViewportView(tblHospitalDirectory);

        btnView.setBackground(new java.awt.Color(0, 102, 102));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblCity.setText("City");

        txtHospName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospNameActionPerformed(evt);
            }
        });

        lblCommunity.setText("Community");

        lblEmpl.setText("Total Employees");

        btnDelete.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblPopulation.setText("Total Population");

        txtCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDocName)
                            .addComponent(lblHosName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPopulation)
                            .addComponent(lblEmpl))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtDocName)
                                    .addComponent(txtHospName)
                                    .addComponent(txtCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtPopulation))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAdd)
                                        .addComponent(btnView))
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHospName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHosName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDocName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCommunity)
                            .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpl)
                            .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPopulation)
                            .addComponent(txtPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblHospital)
                    .addContainerGap(483, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtPopulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPopulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPopulationActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblHospitalDirectory.getSelectedRow();
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblHospitalDirectory.getModel();
        //PatientInfo selectedPatient = (PatientInfo) model1.getValueAt(selectedRowIndex, 0);
        //txtName.setText(String.valueOf(selectedPatient.getPatientName()));

        txtHospName.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtDocName.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtCity.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtCommunity.setText(model.getValueAt(selectedRowIndex, 3).toString());
        txtEmployee.setText(model.getValueAt(selectedRowIndex, 4).toString());
        txtPopulation.setText(model.getValueAt(selectedRowIndex, 5).toString());
        


    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblHospitalDirectory.getSelectedRow();

        if(selectedRowIndex<0) {

            JOptionPane.showMessageDialog(this, "Please select the row!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblHospitalDirectory.getModel();
        HospitalDirectory selecthospital = (HospitalDirectory) model.getValueAt(selectedRowIndex, 0);

        hospitalhistory.deleteHospital(selecthospital);
        JOptionPane.showMessageDialog(this, "Employee Information Deleted!");
        displayTable();
        //        if(tblPatientsDirectory.getSelectedRowCount()==1) {
            //            model.removeRow(tblPatientsDirectory.getSelectedRow());
            //            JOptionPane.showMessageDialog(this, "Employee Information Deleted!");
            //        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        
        
        if (txtHospName.getText().equals("") || txtDocName.getText().equals("") || txtCity.getText().equals("") || txtCommunity.getText().equals("") || txtEmployee.getText().equals("") || txtPopulation.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all details!");
        } else {

            String hospName = txtHospName.getText();
            String docName = txtDocName.getText();
            String hospCity = txtCity.getText();
            String hospCommunity = txtCommunity.getText();
            int totalEmployees = Integer.parseInt(txtEmployee.getText());
            int commPopulation = Integer.parseInt(txtPopulation.getText());

            HospitalDirectory hi = hospitalhistory.addNewHospital();

            hi.setHospName(hospName);
            hi.setDocName(docName);
            hi.setHospCity(hospCity);
            hi.setHospCommunity(hospCommunity);
            hi.setTotalEmployees(totalEmployees);
            hi.setCommPopulation(commPopulation);
            

            JOptionPane.showMessageDialog(this, "Information Added!");

            txtHospName.setText("");
            txtDocName.setText("");
            txtCity.setText("");
            txtCommunity.setText("");
            txtEmployee.setText("");
            txtPopulation.setText("");
            displayTable();

        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtHospNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospNameActionPerformed

    private void txtCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblDocName;
    private javax.swing.JLabel lblEmpl;
    private javax.swing.JLabel lblHosName;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblPopulation;
    private javax.swing.JTable tblHospitalDirectory;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtEmployee;
    private javax.swing.JTextField txtHospName;
    private javax.swing.JTextField txtPopulation;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
       
        
        DefaultTableModel model1 = (DefaultTableModel) tblHospitalDirectory.getModel();
        model1.setRowCount(0);
        
        for (HospitalDirectory hi : hospitalhistory.getHospitalhistory()){
            
            Object[] row = new Object[6];
            //row[0] = pi.getPatientName();
            row[0] = hi;
            row[1] = hi.getDocName();
            row[2] = hi.getHospCity();
            row[3] = hi.getHospCommunity();
            row[4] = hi.getTotalEmployees();
            row[5] = hi.getCommPopulation();
            
            
            
            model1.addRow(row);
            
        }
         
        
    }



}
