/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EncounterHistory;
import model.PatientInfo;

/**
 *
 * @author kshetrahegde
 */
public class ManagePatientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientsJPanel
     */
    EncounterHistory encounterhistory;
    public ManagePatientsJPanel(EncounterHistory encounterhistory) {
        initComponents();
        this.encounterhistory = encounterhistory;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPulse = new javax.swing.JTextField();
        lblPatName = new javax.swing.JLabel();
        txtAssigned = new javax.swing.JTextField();
        lblPatAge = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblPatCity = new javax.swing.JLabel();
        txtPatName = new javax.swing.JTextField();
        lblPatID = new javax.swing.JLabel();
        lblEncID = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        txtReport = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblBP = new javax.swing.JLabel();
        lblAssigned = new javax.swing.JLabel();
        txtPatAge = new javax.swing.JTextField();
        lblPulse = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtPatCity = new javax.swing.JTextField();
        txtPatID = new javax.swing.JTextField();
        txtEncID = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        btnSave1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientsDirectory = new javax.swing.JTable();

        jLabel2.setText("Add Patient Details");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPatName.setText("Name");

        lblPatAge.setText("Age");

        lblPatCity.setText("City");

        lblPatID.setText("ID");

        lblEncID.setText("Encounter ID");

        lblReport.setText("Report");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblBP.setText("Blood Pressure");

        lblAssigned.setText("Doc. Assigned");

        lblPulse.setText("Pulse");

        lblDate.setText("Date");

        txtPatCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatCityActionPerformed(evt);
            }
        });

        txtPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatIDActionPerformed(evt);
            }
        });

        txtBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPActionPerformed(evt);
            }
        });

        btnSave1.setText("Update");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        tblPatientsDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Age", "ID", "Encounter", "Blood Press", "Pulse", "EncounterID", "Diagnosis", "City", "Assigned Doctor"
            }
        ));
        jScrollPane1.setViewportView(tblPatientsDirectory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnAdd)
                        .addGap(55, 55, 55)
                        .addComponent(btnSave1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatName)
                            .addComponent(lblPatAge)
                            .addComponent(lblPatCity)
                            .addComponent(lblPatID)
                            .addComponent(lblEncID)
                            .addComponent(lblBP)
                            .addComponent(lblPulse)
                            .addComponent(lblAssigned)
                            .addComponent(lblDate)
                            .addComponent(lblReport))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReport, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBP)
                                    .addComponent(txtPatName)
                                    .addComponent(txtPatAge)
                                    .addComponent(txtPatCity)
                                    .addComponent(txtPatID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEncID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPulse, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatName)
                            .addComponent(txtPatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatAge)
                            .addComponent(txtPatAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatCity)
                            .addComponent(txtPatCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatID)
                    .addComponent(txtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncID)
                    .addComponent(txtEncID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBP)
                    .addComponent(txtBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulse)
                    .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssigned)
                    .addComponent(txtAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReport))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSave1))
                .addGap(0, 46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        if (txtPatName.getText().equals("") || txtPulse.getText().equals("") || txtPatID.getText().equals("") || txtPatCity.getText().equals("") || txtPatAge.getText().equals("") || txtEncID.getText().equals("") ||  txtBP.getText().equals("") || txtAssigned.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all details!");
        } else {

            String patientName = txtPatName.getText();
            int age = Integer.parseInt(txtPatAge.getText());
            String city = txtPatCity.getText();
            int patientId = Integer.parseInt(txtPatID.getText());
            int encounterId = Integer.parseInt(txtEncID.getText());
            int bloodPressure = Integer.parseInt(txtBP.getText());
            int pulse = Integer.parseInt(txtPulse.getText());
            String assignedDoctor = txtAssigned.getText();
            LocalDate d1 = LocalDate.parse(txtDate.getText());
            String diagnosis = txtReport.getText();

            PatientInfo pi = encounterhistory.addNewPatient();

            pi.setPatientName(patientName);
            pi.setAge(age);
            pi.setCity(city);
            pi.setPatientId(patientId);
            pi.setEncounterId(encounterId);
            pi.setBloodPressure(bloodPressure);
            pi.setPulse(pulse);
            pi.setAssignedDoctor(assignedDoctor);
            pi.setD1(d1);
            pi.setDiagnosis(diagnosis);

            JOptionPane.showMessageDialog(this, "Information Added!");

            txtPatName.setText("");
            txtPatAge.setText("");
            txtPatCity.setText("");
            txtPatID.setText("");
            txtEncID.setText("");
            txtBP.setText("");
            txtPulse.setText("");
            txtAssigned.setText("");
            txtDate.setText("");
            displayTable();

        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtPatCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatCityActionPerformed

    private void txtPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatIDActionPerformed

    private void txtBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblPatientsDirectory.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblPatientsDirectory.getModel();
        //PatientInfo selectPatient = (PatientInfo)model.getValueAt(selectedRowIndex, 0);
        
        if(tblPatientsDirectory.getSelectedRowCount() == 1) {
            String patientName = txtPatName.getText();
            int age = Integer.parseInt(txtPatAge.getText());
            String city = txtPatCity.getText();
            int patientId = Integer.parseInt(txtPatID.getText());
            int encounterId = Integer.parseInt(txtEncID.getText());
            int bloodPressure = Integer.parseInt(txtBP.getText());
            int pulse = Integer.parseInt(txtPulse.getText());
            String assignedDoctor = txtAssigned.getText();
            LocalDate d1 = LocalDate.parse(txtDate.getText());
            String diagnosis = txtReport.getText();
            
            
            model.setValueAt(patientName, tblPatientsDirectory.getSelectedRow(), 0);
            model.setValueAt(age, tblPatientsDirectory.getSelectedRow(), 1);
            model.setValueAt(city, tblPatientsDirectory.getSelectedRow(), 2);
            model.setValueAt(patientId, tblPatientsDirectory.getSelectedRow(), 3);
            model.setValueAt(encounterId, tblPatientsDirectory.getSelectedRow(), 4);
            model.setValueAt(bloodPressure, tblPatientsDirectory.getSelectedRow(), 5);
            model.setValueAt(pulse, tblPatientsDirectory.getSelectedRow(), 6);
            model.setValueAt(assignedDoctor, tblPatientsDirectory.getSelectedRow(), 7);
            model.setValueAt(d1, tblPatientsDirectory.getSelectedRow(), 8);
            model.setValueAt(diagnosis, tblPatientsDirectory.getSelectedRow(), 9);
        }
    }//GEN-LAST:event_btnSave1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSave1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssigned;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEncID;
    private javax.swing.JLabel lblPatAge;
    private javax.swing.JLabel lblPatCity;
    private javax.swing.JLabel lblPatID;
    private javax.swing.JLabel lblPatName;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblReport;
    private javax.swing.JTable tblPatientsDirectory;
    private javax.swing.JTextField txtAssigned;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEncID;
    private javax.swing.JTextField txtPatAge;
    private javax.swing.JTextField txtPatCity;
    private javax.swing.JTextField txtPatID;
    private javax.swing.JTextField txtPatName;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtReport;
    // End of variables declaration//GEN-END:variables
    
    private void displayTable() {
       
        
        DefaultTableModel model1 = (DefaultTableModel) tblPatientsDirectory.getModel();
        model1.setRowCount(0);
        
        for (PatientInfo pi : encounterhistory.getHistory()){
            
            Object[] row = new Object[10];
            row[0] = pi.getPatientName();
            row[1] = pi.getAge();
            row[2] = pi.getPatientId();
            row[3] = pi.getD1();
            row[4] = pi.getBloodPressure();
            row[5] = pi.getPulse();
            row[6] = pi.getEncounterId();
            row[7] = pi.getDiagnosis();
            row[8] = pi.getCity();
            row[9] = pi.getAssignedDoctor();
            
            
            model1.addRow(row);
            
        }
         
        
    }


}
